const constant = {
    EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY',
    PASSWORD_IS_EMPTY = 'PASSWORD_IS_EMPTY',
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
    'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8',
    WRONG_PASSWORD = 'WRONG_PASSWORD',
    USER_EXISTS_ALREADY = 'USER_EXISTS_ALREADY',
    USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
    TOKEN_IS_EMPTY = 'TOKEN_IS_EMPTY',
    EMAIL_IS_IN_WRONG_FORMAT = 'EMAIL_IS_IN_WRONG_FORMAT',
}

module.exports = { constant }